language: groovy
os: linux
dist: focal
jdk:
  - openjdk11

services:
  - docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq -y install graphviz
  - sudo pip install awscli
  - sudo sysctl -w vm.max_map_count=655350

install:
  - curl -fsSL get.nextflow.io | bash
  - mkdir -p ~/bin; cp nextflow ~/bin

script: 
- nextflow run main.nf -profile test